python3 /ofo-share/utils/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/itd-crossmapping-photogrammetry-prep/configs/20220622-0038.yml
python3 /ofo-share/utils/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/itd-crossmapping-photogrammetry-prep/configs/20230622-0127.yml
python3 /ofo-share/utils/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/itd-crossmapping-photogrammetry-prep/configs/20230623-0107.yml
python3 /ofo-share/utils/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/itd-crossmapping-photogrammetry-prep/configs/20230623-0132.yml
python3 /ofo-share/utils/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/itd-crossmapping-photogrammetry-prep/configs/20230623-0133.yml
python3 /ofo-share/utils/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/itd-crossmapping-photogrammetry-prep/configs/20230624-0137.yml
python3 /ofo-share/utils/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/itd-crossmapping-photogrammetry-prep/configs/20230625-0113.yml
python3 /ofo-share/utils/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/itd-crossmapping-photogrammetry-prep/configs/20230625-0116.yml
python3 /ofo-share/utils/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/itd-crossmapping-photogrammetry-prep/configs/20230625-0145.yml
python3 /ofo-share/utils/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/itd-crossmapping-photogrammetry-prep/configs/20230706-0151.yml
python3 /ofo-share/utils/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/itd-crossmapping-photogrammetry-prep/configs/20230706-0152.yml
python3 /ofo-share/utils/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/itd-crossmapping-photogrammetry-prep/configs/20230706-0156.yml
python3 /ofo-share/utils/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/itd-crossmapping-photogrammetry-prep/configs/20230707-0158.yml
python3 /ofo-share/utils/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/itd-crossmapping-photogrammetry-prep/configs/20230707-0161.yml
python3 /ofo-share/utils/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/itd-crossmapping-photogrammetry-prep/configs/20230707-0193.yml
python3 /ofo-share/utils/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/itd-crossmapping-photogrammetry-prep/configs/20230708-0162.yml
python3 /ofo-share/utils/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/itd-crossmapping-photogrammetry-prep/configs/20230708-0166.yml
python3 /ofo-share/utils/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/itd-crossmapping-photogrammetry-prep/configs/20230709-0171.yml
python3 /ofo-share/utils/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/itd-crossmapping-photogrammetry-prep/configs/20230709-0199.yml
python3 /ofo-share/utils/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/itd-crossmapping-photogrammetry-prep/configs/20230710-0176.yml
python3 /ofo-share/utils/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/itd-crossmapping-photogrammetry-prep/configs/20230710-0206.yml
python3 /ofo-share/utils/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/itd-crossmapping-photogrammetry-prep/configs/20230803-0257.yml
python3 /ofo-share/utils/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/itd-crossmapping-photogrammetry-prep/configs/20230803-0262.yml
python3 /ofo-share/utils/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/itd-crossmapping-photogrammetry-prep/configs/20230803-0295.yml
python3 /ofo-share/utils/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/itd-crossmapping-photogrammetry-prep/configs/20230804-0294.yml
python3 /ofo-share/utils/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/itd-crossmapping-photogrammetry-prep/configs/20230804-0302.yml
python3 /ofo-share/utils/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/itd-crossmapping-photogrammetry-prep/configs/set14_thin22.yml
