# Purpose: a controller script that runs the raw imagery ingestion pipeline from script 01 to 11.

repo_root = "/ofo-share/repos-derek/ofo-r"

cat("\n\n****Starting script 1****\n\n")
source(file.path(repo_root,"sandbox/drone-imagery-ingestion/01_read-folder-exif-to-csv.R"))
cat("\n\n****Starting script 2****\n\n")
source(file.path(repo_root,"sandbox/drone-imagery-ingestion/02_plan-imagery-folder-standardization.R"))
cat("\n\n****Starting script 3****\n\n")
source(file.path(repo_root,"sandbox/drone-imagery-ingestion/03_compile-baserow-metadata.R"))
cat("\n\n****Starting script 4****\n\n")
source(file.path(repo_root,"sandbox/drone-imagery-ingestion/04_determine-missions-to-process.R"))
cat("\n\n****Starting script 5****\n\n")
source(file.path(repo_root,"sandbox/drone-imagery-ingestion/05_parse-exif-metadata-per-image.R"))
cat("\n\n****Starting script 6****\n\n")
source(file.path(repo_root,"sandbox/drone-imagery-ingestion/06_summarize-exif-metadata-per-mission.R"))
cat("\n\n****Starting script 7****\n\n")
source(file.path(repo_root,"sandbox/drone-imagery-ingestion/07_merge-exif-and-baserow.R"))
cat("\n\n****Starting script 8****\n\n")
source(file.path(repo_root,"sandbox/drone-imagery-ingestion/08_copy-images-to-standardized-folders.R"))
cat("\n\n****Starting script 9****\n\n")
source(file.path(repo_root,"sandbox/drone-imagery-ingestion/09_fix-orientation-flag.R"))
cat("\n\n****Starting script 10****\n\n")
source(file.path(repo_root,"sandbox/drone-imagery-ingestion/10_raw-imagery-thumbnails-and-zip.R"))
cat("\n\n****Starting script 11****\n\n")
source(file.path(repo_root,"sandbox/drone-imagery-ingestion/11_raw-imagery-to-publishable-filetree.R"))
