python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000141.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000142.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000143.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000144.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000145.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000147.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000148.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000149.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000151.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000152.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000153.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000155.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000157.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000158.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000160.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000161.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000162.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000164.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000165.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000167.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000168.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000169.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000171.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000173.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000174.yml
