python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000234.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000236.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000237.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000238.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000239.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000240.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000242.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000244.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000245.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000246.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000248.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000250.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000251.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000252.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000254.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000256.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000257.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000259.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000260.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000261.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000262.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000263.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000266.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000267.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000268.yml
