python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000298.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000299.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000300.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000301.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000302.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000303.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000304.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000305.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000306.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000307.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000308.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000309.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000310.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000311.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000312.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000313.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000314.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000315.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000316.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000317.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000318.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000319.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000320.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000321.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000322.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000323.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000324.yml
