python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000106.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000107.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000109.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000110.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000112.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000113.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000114.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000116.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000118.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000119.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000121.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000123.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000124.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000125.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000126.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000127.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000128.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000129.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000131.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000133.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000135.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000136.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000137.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000138.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2023-ny-ofo/000139.yml
