python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2022-early-regen/000020.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2022-early-regen/000021.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2022-early-regen/000022.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2022-early-regen/000023.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2022-early-regen/000024.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2022-early-regen/000025.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2022-early-regen/000026.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2022-early-regen/000028.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2022-early-regen/000029.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2022-early-regen/000030.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2022-early-regen/000031.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2022-early-regen/000032.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2022-early-regen/000033.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2022-early-regen/000034.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2022-early-regen/000035.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2022-early-regen/000036.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2022-early-regen/000040.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2022-early-regen/000044.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2022-early-regen/000045.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2022-early-regen/000046.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2022-early-regen/000047.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2022-early-regen/000048.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2022-early-regen/000050.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2022-early-regen/000052.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2022-early-regen/000055.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2022-early-regen/000056.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2022-early-regen/000058.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2022-early-regen/000059.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2022-early-regen/000060.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2022-early-regen/000061.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2022-early-regen/000062.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2022-early-regen/000065.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2022-early-regen/000067.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2022-early-regen/000069.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2022-early-regen/000070.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2022-early-regen/000071.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2022-early-regen/000072.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2022-early-regen/000073.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2022-early-regen/000074.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2022-early-regen/000075.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2022-early-regen/000076.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2022-early-regen/000078.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2022-early-regen/000079.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2022-early-regen/000081.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2022-early-regen/000082.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2022-early-regen/000083.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2022-early-regen/000084.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2022-early-regen/000085.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2022-early-regen/000086.yml
python3 /ofo-share/repos-derek/automate-metashape/python/metashape_workflow.py /ofo-share/repos-derek/ofo-r/sandbox/drone-imagery-ingestion/full-run-configs/2022-early-regen/000087.yml
